---
abstract: 'Event-based memcached caching layer for EntityModel'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Cache-Memcached-Async
requires:
  EntityModel: 0.016
  EntityModel::Class: 0.010
  Net::Async::Memcached: 0.001
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=EntityModel-Cache-Memcached-Async
  homepage: http://search.cpan.org/dist/EntityModel-Cache-Memcached-Async/
version: 0.001
